#!/usr/bin/env python

import os
import subprocess
import sys

import nbformat

filename = sys.argv[1]
base_name, extension = os.path.splitext(filename)
if extension == ".ipynb":
    subprocess.run(["jupyter", "nbconvert", "--to", "python", filename, "--show-input"])
    subprocess.run(["black", base_name + ".py", "-q"])

elif extension == ".py":
    nb = nbformat.v4.new_notebook()
    nb["cells"] = []
    input = open(filename)
    next(input)
    next(input)
    for line in input:
        if line != "\n":
            if line.startswith("# In["):
                nb["cells"].append(nbformat.v4.new_code_cell(""))
            else:
                nb["cells"][-1]["source"] += line
    nbformat.write(nb, open(base_name + ".ipynb", "w"))

else:
    raise ValueError("Unknown file type")
