#!/usr/bin/env python

import os
import sys

import nbformat


def py2ipynb(code: list) -> nbformat.v4:
    nb = nbformat.v4.new_notebook()
    nb["cells"] = []
    cell_value = ""

    for line in code:
        if line.startswith("# In["):
            if cell_value:
                nb["cells"].append(nbformat.v4.new_code_cell(cell_value))
            cell_value = ""
            continue
        elif "!/usr/bin/env python" or "# coding: utf-8" in line:
            pass
        else:
            breakpoint()
        cell_value += line

    if cell_value:
        nb["cells"].append(nbformat.v4.new_code_cell(cell_value))
    return nb


file_name = sys.argv[1]
with open(file_name) as file:
    nb = py2ipynb(file.readlines())
    ipynb = os.path.splitext(os.path.basename(file_name))[0] + ".ipynb"
    with open(ipynb, "w") as f:
        nbformat.write(nb, f)
        print("Generated: ", ipynb)
    # jupyter nbconvert --to script plot_loss.ipynb --show-input
