#!/bin/sh

if [ $1 = "setup" ]; then
    mkdir -p $(dirname $0)/storage/data
    cd $(dirname $0)/storage/data
    if [ ! -e imagenet.tar.gz ]; then
        scp ds:/data0/issa/dataset/imagenet.tar.gz imagenet.tar.gz
    fi
    if [ ! -e imagenet ]; then
        tar -xzf imagenet.tar.gz && clear
    else
        echo "-> imagenet already exists"
    fi

elif [ $1 = "install" ]; then
    cd $(dirname $0)
    pip freeze >uninstall.txt
    pip uninstall -r uninstall.txt -y
    rm uninstall.txt
    pip install -r requirements.txt && clear

elif [ $1 = "format" ]; then
    echo "\n----black-----"
    black $(dirname $0) -q
    echo "\n----isort-----"
    isort $(dirname $0) -s ./run
    echo "\n----flake8----"
    pflake8 $(dirname $0)
    echo

elif [ $1 = "test" ]; then
    if [ $# = 2 ]; then
        cd $(dirname $0)/src
        python attack.py -c config/default/APGD.yaml -g $2 --thread 10 --log_level 10
    else
        echo "Usage: $0 test [gpu]"
        exit 1
    fi

else
    echo "Usage: $0 [setup|install|format|test]"
fi
