#!/bin/sh

if [ $1 = "setup" ]; then
    mkdir -p $(dirname $0)/storage/data
    cd $(dirname $0)/storage/data
    if [ ! -e imagenet.tar.gz ]; then
        scp ds:/data0/issa/dataset/imagenet.tar.gz imagenet.tar.gz
        # wget http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_val.tar
    fi
    if [ ! -e imagenet ]; then
        tar -xzf imagenet.tar.gz
        # tar -xf ILSVRC2012_img_val.tar -C val
    else
        echo "-> imagenet already exists"
    fi

elif [ $1 = "install" ]; then
    cd $(dirname $0)
    pip install --upgrade pip
    pip list --format freeze | grep -v -e pip -e setuptools | xargs pip uninstall -y
    pip install -r requirements.txt

elif [ $1 = "format" ]; then
    echo && echo "----black-----"
    black $(dirname $0) -q
    echo && echo "----isort-----"
    isort $(dirname $0) -s ./run
    echo && echo "----flake8----"
    pflake8 $(dirname $0)
    echo

else
    echo "Usage: $0 [setup|install|format|test]"
fi
