#!/bin/sh

cd $(dirname $0)
root_dir=$(pwd -P)

if [ "$1 " = "install " ]; then
    cd $root_dir
    pip install --upgrade pip
    pip install -r requirements.txt

elif [ "$1 " = "setup " ]; then
    cd $root_dir/storage/data
    if [ ! -e imagenet ]; then
        mkdir imagenet
        tar -xvf ILSVRC2012_img_val.tar -C imagenet
        tar -zxvf ILSVRC2012_devkit_t12.tar.gz
        cd $root_dir/setup
        python3 setup_imagenet.py
        python3 download_models.py
    else
        echo "-> imagenet already exists"
    fi

elif [ "$1 " = "format " ]; then
    black $root_dir/src -q
    isort $root_dir/src -q
    pflake8 $root_dir/src
    echo "formatted"

else
    echo "Usage: $0 [install|setup|format]"
fi
