attacker: BoundaryAttack

norm: Linf
epsilon: 0.03137254901960784
dataset: cifar10_easy
model:
    robustbench:
        Carmon2019Unlabeled: 3000

# hyperparameter
orthogonal_step_size: 0.01
target_step_size: 0.01
step_adaptation: 0.667
steps: 10
num_trial: 5
sample_size: 2
init_size: 1
