attacker: GradientApproximation

norm: Linf
epsilon: 0.03137254901960784
dataset: cifar10_easy
model:
    robustbench:
        Carmon2019Unlabeled: 1

# hyperparameter
sampling: 5000
steps: 2
estimation_step_size: 0.01
step_size: 0.01568627450980392
random_initialize: True
