attacker: AdvancedLocalSearch

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet
n_examples: 5000

model:
    robustbench:
        Salman2020Do_R18: 2500

# hyperparameter
steps: 100
criterion: cw
segments: [4, 16, 64, 256]
init_checkpoint: 1.1
checkpoint: 1.1
additional_search: impacter
attention_pixel: impacter
ratio: 0.66
