attacker: GenAttack

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet
n_examples: 5000

model:
    robustbench:
        Wong2020Fast: 100
        Engstrom2019Robustness: 100
        Salman2020Do_R18: 100
        Salman2020Do_R50: 100
        Salman2020Do_50_2: 100

# hyperparameter
population: 10
steps: 10
tau: 0.1
alpha_init: 0.4
rho_init: 0.5
decay: 0.9
