attacker: GenAttack

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet
n_examples: 5000

model:
    robustbench:
        Salman2020Do_R18: 100

# hyperparameter
population: 10
steps: 100
tau: 0.1
alpha_init: 0.4
rho_init: 0.5
decay: 0.9
