attacker: LocalSearch

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet
n_examples: 5000

model:
    robustbench:
        Wong2020Fast: 1000
        Engstrom2019Robustness: 1000
        Salman2020Do_R18: 1000
        Salman2020Do_R50: 1000
        Salman2020Do_50_2: 1000

# hyperparameter
steps: 100
criterion: cw
segments: [4, 16, 64, 256, 1024]
init_checkpoint: 3
checkpoint: 3
additional_search: best
