attacker: LocalSearchRevise

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet
n_examples: 5

model:
    robustbench:
        # Wong2020Fast: 1500
        # Engstrom2019Robustness: 1500
        Salman2020Do_R18: 1500
        # Salman2020Do_R50: 1500
        # Salman2020Do_50_2: 1500

# hyperparameter
steps: 10
criterion: cw
segments: [4, 16, 64, 256, 1024]
init_checkpoint: 3
checkpoint: 3
additional_search: best
