attacker: ParsimoniousAttack

norm: Linf
epsilon: 0.01568627450980392
n_examples: 5000
seed: 0
iter: 100
criterion: ce

model: Salman2020Do_R18
batch_size: 3500

# hyperparameter
initial_split: 32
insert_and_deletion: 1
