attacker: ParsimoniousAttack

norm: Linf
epsilon: 0.01568627450980392
n_examples: 5000

model:
    torchvision:
        inception_v3: 1000
        resnet50: 1000

    robustbench:
        Wong2020Fast: 1000
        Engstrom2019Robustness: 1000
        Salman2020Do_R18: 1000
        Salman2020Do_R50: 1000
        Salman2020Do_50_2: 1000

# hyperparameter
step: 100
criterion: ce
initial_split: 32
insert_and_deletion: 1
