attacker: ProposedMethod

norm: Linf
epsilon: 0.01568627450980392
n_examples: 5000

model:
    robustbench:
        Wong2020Fast: 2500
        Engstrom2019Robustness: 2500
        Salman2020Do_R18: 2500
        Salman2020Do_R50: 2500
        Salman2020Do_50_2: 2500

# hyperparameter
steps: 100
criterion: cw
segments: [4, 16, 64, 256]
