attacker: ProposedMethod

norm: Linf
epsilon: 0.01568627450980392
n_examples: 5000

model:
    Wong2020Fast: 2000
    Salman2020Do_R18: 2000

# hyperparameter
step: 100
criterion: cw
update_area: superpixel
update_method: adaptive_search
removal: True

# superpixel
segments: [4, 16, 64, 256, 1024, 4096, 16384]

# equally_divided_squares
initial_split: 32

# saliency_map
saliency_batch: 100
threshold: 0.1
k_int: 16

# random_square
p_init: 0.8
