attacker: TabuProposedMethod

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet
n_examples: 5000

model:
    robustbench:
        Salman2020Do_R18: 1000

# hyperparameter
step: 100
criterion: cw
segments: [4, 16]
checkpoints: [30, 70]
