attacker: ProposedMethod

norm: Linf
epsilon: 0.01568627450980392
n_examples: 5000

model:
    robustbench:
        # Wong2020Fast: 5000
        # Engstrom2019Robustness: 5000
        Salman2020Do_R18: 5000
        # Salman2020Do_R50: 5000
        # Salman2020Do_50_2: 5000

# hyperparameter
steps: 100
criterion: cw
update_area: superpixel
initial_point: lower
update_method: uniform_distribution

# superpixel
segments: [4, 16, 64, 256]
save_wasted: True
