attacker: ProposedMethod

norm: Linf
epsilon: 0.01568627450980392
n_examples: 5000

model:
    # torchvision
    # resnet50: 5000
    # vgg16_bn: 5000

    # robustbench
    # Wong2020Fast: 5000
    # Engstrom2019Robustness: 5000
    Salman2020Do_R18: 3000
    # Salman2020Do_R50: 5000
    # Salman2020Do_50_2: 5000

# hyperparameter
step: 100
criterion: cw
update_area: superpixel
channel_wise: True
initial_point: lower
update_method: greedy_local_search

# superpixel
segments: [4, 16, 64, 256, 1024]
save_wasted: True

# random_square
p_init: 0.8

# split_square
initial_split: 32

# saliency_map
saliency_batch: 100
threshold: 0.1
k_init: 16
