attacker: ProposedMethod

norm: Linf
epsilon: 0.01568627450980392
n_examples: 10

model:
    robustbench:
        # Wong2020Fast: 2500
        # Engstrom2019Robustness: 2500
        Salman2020Do_R18: 2500
        # Salman2020Do_R50: 2500
        # Salman2020Do_50_2: 2500

# hyperparameter
steps: 10
criterion: cw
update_area: superpixel
initial_point: lower
update_method: greedy_local_search

# superpixel
segments: [4, 16, 64, 256]
save_wasted: True
