attacker: ColorProposedMethod

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet
n_examples: 5000

model:
    robustbench:
        Salman2020Do_R18: 5000

# hyperparameter
step: 100
criterion: cw
p_init: 0.8
segments: [4, 16, 64, 256, 512]
