attacker: ProposedMethod

norm: Linf
epsilon: 0.01568627450980392
n_examples: 5000

model:
    torchvision:
        inception_v3: 5000
        resnet50: 5000

    robustbench:
        Wong2020Fast: 5000
        Engstrom2019Robustness: 5000
        Salman2020Do_R18: 5000
        Salman2020Do_R50: 5000
        Salman2020Do_50_2: 5000

# hyperparameter
steps: 100
criterion: cw
update_area: random_square
initial_point: random
update_method: uniform_distribution

# superpixel
segments: [4, 16, 64, 256, 1024]
save_wasted: True

# random_square
p_init: 0.8
