attacker: SaliencyAttack

norm: Linf
epsilon: 0.01568627450980392
n_examples: 5000

model:
    # torchvision
    resnet50: 1000
    vgg16_bn: 500

    # robustbench
    Wong2020Fast: 1000
    Engstrom2019Robustness: 500
    Salman2020Do_R50: 1000
    Salman2020Do_R18: 1000
    Salman2020Do_50_2: 500

# hyperparameter
step: 100
criterion: cw
k_int: 16
saliency_batch: 100
threshold: 0.1

