attacker: SquareAttack

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet
n_examples: 5000

model:
    robustbench:
        Salman2020Do_R18: 5000

# hyperparameter
steps: 1000
p_init: 0.8
restart: 1
