attacker: GenAttack

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet_easy
model:
    robustbench:
        Salman2020Do_R18: 1156

# hyperparameter
steps: 600
population: 10
mutation_probability: 0.10
mutation_range: 0.15
sampling_temperature: 0.3
