attacker: GradientApproximation

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet_easy
model:
    robustbench:
        Salman2020Do_R18: 1

# hyperparameter
sampling: 300
steps: 1
estimation_step_size: 0.01
step_size: 0.01568627450980392
random_initialize: True
