attacker: HALS

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet_easy
model:
    robustbench:
        Salman2020Do_R18: 1

# hyperparameter
forward: 100
criterion: cw
initial_split: 32
local_search_iteration: 1
