attacker: TabuAttack

norm: Linf
epsilon: 0.01568627450980392
dataset: imagenet_easy
model:
    robustbench:
        Salman2020Do_R18: 1

# hyperparameter
criterion: cw
forward: 30000
tabu_size: 20
neighbor_search: 3
N_flip: 100
