attacker: GenAttack

norm: Linf
epsilon: 0.03137254901960784
dataset: cifar10_hard
model:
    robustbench:
        Carmon2019Unlabeled: 3000

# hyperparameter
steps: 10
population: 10
mutation_probability: 0.10
mutation_range: 0.15
sampling_temperature: 0.3
