attacker: TabuAttack

norm: Linf
epsilon: 0.03137254901960784
dataset: cifar10_easy
model:
    robustbench:
        Carmon2019Unlabeled: 1

# hyperparameter
criterion: cw
forward: 6000
tabu_size: 20
neighbor_search: 3
N_flip: 100
