attacker: APGD

n_examples: 110
norm: Linf
epsilon: 0.03137254901960784
iteration: 100

step_size: 0.06274509803921569
rho: 0.75

criterion:
    #
    # ce
    cw
    # dlr
dataset:
    #
    cifar10
    # cifar100
    # imagenet
model:
    # model_name: batch_size
    Carmon2019Unlabeled: 200
