attacker: APGD

n_examples: 100
norm: Linf
epsilon: 0.03137254901960784
iteration: 100
step_size: 0.06274509803921569
rho: 0.75

criterion: cw
dataset: cifar10
model:
    robustbench:
        Carmon2019Unlabeled: 200
