attacker: HALS

n_examples: 110
norm: Linf
epsilon: 0.03137254901960784
max_iter: 1
iteration: 10

initial_split: 4

criterion:
    #
    # ce
    cw
    # dlr
dataset:
    #
    cifar10
    # cifar100
    # imagenet
model:
    # model_name: batch_size
    Carmon2019Unlabeled: 20
    # Ding2020MMA: 1000
    # Salman2020Do_R18: 20
