attacker: HALS

n_examples: 10_000
norm: Linf
epsilon: 0.03137254901960784
max_iter: 1
iteration: 6
initial_split: 4

criterion: cw
dataset: cifar10
model:
    robustbench:
        Carmon2019Unlabeled: 8000
